spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paddle_db
    username: paddle_admin
    password: password1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/paddle-app-1074c

logging:
  level:
    org.springframework.security: DEBUG

app:
  matchmaking:
    fixed-delay-ms: 10000